// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package store

import api "yougo-api/api"

type GoConverterImpl struct{}

func (c *GoConverterImpl) GoFromDB(source dbGo) api.Go {
	var apiGo api.Go
	apiGo.Id = source.Id
	apiGo.Alias = source.Alias
	apiGo.Href = source.Href
	return apiGo
}
func (c *GoConverterImpl) GoToDB(source api.Go) dbGo {
	var storedbGo dbGo
	storedbGo.Id = source.Id
	storedbGo.Alias = source.Alias
	storedbGo.Href = source.Href
	return storedbGo
}
func (c *GoConverterImpl) GosFromDB(source []dbGo) []api.Go {
	var apiGoList []api.Go
	if source != nil {
		apiGoList = make([]api.Go, len(source))
		for i := 0; i < len(source); i++ {
			apiGoList[i] = c.GoFromDB(source[i])
		}
	}
	return apiGoList
}
func (c *GoConverterImpl) GosToDB(source []api.Go) []dbGo {
	var storedbGoList []dbGo
	if source != nil {
		storedbGoList = make([]dbGo, len(source))
		for i := 0; i < len(source); i++ {
			storedbGoList[i] = c.GoToDB(source[i])
		}
	}
	return storedbGoList
}
